spring:
  application:
    name: zipkin
  boot:
    admin:
      client:
        url: http://192.168.1.106:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.106:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info