spring:
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/HbAladdin/config
          search-paths: respo
          username: zhouruizhong
          password: zhouruizhong@809
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://182.61.137.69:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info